from .componente import ComponenteAdmin
from .garantia import GarantiaAdmin
from .local import LocalAdmin
from .marca import MarcaAdmin
from .modificacion import ModificacionAdmin
from .patrimonial import PatrimonialAdmin
from .proveedor import ProveedorAdmin
from .recurso import RecursoAdmin
from .seccion import SeccionAdmin
from .tipoComponente import TipoComponenteAdmin
from .tipoRecurso import TipoRecursoAdmin
from .trazabilidad import TrazabilidadAdmin
