from .accesorio import AccesorioAdmin
from .alumnoComision import AlumnoComision
from .area import AreaAdmin
from .aula import AulaAdmin
from .carruselImagenes import CarruselImagenes
from .cuerpo import CuerpoAdmin
from .docente import Docente
from .docenteComision import DocenteComision
from .especialidad import EspecialidadAdmin
from .comision import ComisionAdmin
from .imagenCarrusel import ImagenCarrusel
from .imagenContingencia import ImagenContingenciaAdmin
from .laboratorio import LaboratorioAdmin
from .laboratorioInformatico import LaboratorioInformaticoAdmin
from .materia import MateriaAdmin
from .nivel import NivelAdmin
from .novedad import NovedadAdmin
from .plan import Plan
from .recursoAli import RecursoAliAdmin
from .tipoAccesorio import TipoAccesorio
from .tipoLaboratorio import TipoLaboratorioAdmin
from .tipoRecursoAli import TipoRecursoAliAdmin
from .visorTv import VisorTvAdmin
