from .accesorio import AccesorioAdmin
from .area import AreaAdmin
from .aula import AulaAdmin
from .carruselImagenes import CarruselImagenes
from .cuerpo import CuerpoAdmin
from .imagenCarrusel import ImagenCarrusel
from .imagenContingencia import ImagenContingenciaAdmin
from .laboratorio import LaboratorioAdmin
from .laboratorioInformatico import LaboratorioInformaticoAdmin
from .nivel import NivelAdmin
from .novedad import NovedadAdmin
from .recursoAli import RecursoAliAdmin
from .recursoUM import RecursoUMAdmin
from .tipoAccesorio import TipoAccesorioAdmin
from .tipoAula import TipoAulaAdmin
from .tipoLaboratorio import TipoLaboratorioAdmin
from .tipoRecursoAli import TipoRecursoAliAdmin
from .tipoRecursoUM import TipoRecursoUMAdmin
from .visorTv import VisorTvAdmin
