from .area import AreaAdmin
from .aula import AulaAdmin
from .carruselImagenes import CarruselImagenes
from .cuerpo import CuerpoAdmin
from .imagenCarrusel import ImagenCarrusel
from .imagenContingencia import ImagenContingenciaAdmin
from .laboratorio import LaboratorioAdmin
from .laboratorioInformatico import LaboratorioInformaticoAdmin
from .nivel import NivelAdmin
from .novedad import NovedadAdmin
from .recursoAli import RecursoAliAdmin
from .recursoSAE import RecursoSAEAdmin
from .tipoLaboratorio import TipoLaboratorioAdmin
from .tipoRecursoAli import TipoRecursoAliAdmin
from .tipoRecursoSAE import TipoRecursoSAEAdmin
from .visorTv import VisorTvAdmin
