# coding=utf-8

from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import (
    AliTemplateView,
    AliVideoconferenciasDetailView,
    AreaDetailView,
    AsingRole,
    AulaDetailView,
    CuerpoDetailView,
    FechasSemestreConfig,
    IndexView,
    LaboratorioDetailView,
    LaboratorioInformaticoDetailView,
    LaboratorioInformaticoListView,
    LoginIndexView,
    NivelDetailView,
    NovedadView,
    PrestamoCreate,
    PrestamoConfirm,
    PrestamoDetail,
    PrestamoElementAdd,
    PrestamoElementsRemove,
    PrestamoFinalize,
    PrestamoList,
    PrestamoRegister,
    RecursoAssign,
    recurso_eventos_json,
    RecursoAliDetailView,
    ReservaCreate,
    ReservaList,
    ReservaListDocente,
    RemoveRole,
    SolicitudAliReclamosSugerencias,
    SolicitudAulaView,
    SolicitudCreate,
    SolicitudDetail,
    SolicitudInstalacionSoftwareView,
    SolicitudLaboratorioInformaticoView,
    SolicitudList,
    SolicitudMaterialMultimediaView,
    SolicitudReject,
    TipoLaboratorioDetailView,
    TipoRecursoAliDetailView,
    TvCuerposListView,
    TvVisorCuerposDetailView,
    TvVisorDetailView,
    UserList,
)
from .serializer import get_materia_json, get_horarios_json, get_horarios, get_alumnos, get_comisiones_docentes, get_cursado, get_especialidades, get_materias

from .views.horarios import HorariosWeekView, HorariosComisionListView

urlpatterns = [
    url(
        r'^$',
        IndexView.as_view(),
        name='index'
    ),
    url(
        r'^inicio/$',
        login_required(LoginIndexView.as_view()),
        name='login_index'
    ),
    url(
        r'^cuerpo/(?P<numero>\d+)/$',
        CuerpoDetailView.as_view(),
        name='cuerpo_detalle'
    ),
    url(
        r'^cuerpo/(?P<numero_cuerpo>\d+)/nivel/(?P<numero_nivel>-?\d+)/$',
        NivelDetailView.as_view(),
        name='nivel_detalle'
    ),
    url(
        r'^aula/(?P<pk>\d+)/$',
        AulaDetailView.as_view(),
        name='aula_detalle'
    ),
    url(
        r'^area/(?P<slug>[-\w]+)/$',
        AreaDetailView.as_view(),
        name='area_detalle'
    ),
    url(
        r'^recurso/(?P<pk>\d+)/eventos/$',
        recurso_eventos_json,
        name='recurso_eventos_json'
    ),
    url(
        r'^ali/$',
        AliTemplateView.as_view(),
        name='ali_index'
    ),
    url(
        r'^ali/videoconferencias/$',
        AliVideoconferenciasDetailView.as_view(),
        name='ali_videoconferencias_detalle'
    ),
    url(
        r'^laboratorios/informatica/$',
        LaboratorioInformaticoListView.as_view(),
        name='laboratorio_informatico_listado'
    ),
    url(
        r'^laboratorio/informatica/(?P<alias>[A-Za-z0-9]+)/$',
        LaboratorioInformaticoDetailView.as_view(),
        name='laboratorio_informatico_detalle'
    ),
    url(
        r'^laboratorios/(?P<slug>[-\w]+)/$',
        TipoLaboratorioDetailView.as_view(),
        name='tipo_laboratorio_detalle'
    ),
    url(
        r'^laboratorio/(?P<tipo>[A-Za-z0-9]+)/(?P<alias>[A-Za-z0-9]+)/$',
        LaboratorioDetailView.as_view(),
        name='laboratorio_detalle'
    ),
    url(
        r'^ali/(?P<slug>[-\w]+)/$',
        TipoRecursoAliDetailView.as_view(),
        name='tipo_recurso_ali_detalle'
    ),
    url(
        r'^ali/(?P<tipo>[-\w]+)/(?P<identificador>[A-Za-z0-9_-]+)/$',
        RecursoAliDetailView.as_view(),
        name='recurso_ali_detalle'
    ),
    url(
        r'^solicitud/ali/reclamos_sugerencias/$',
        SolicitudAliReclamosSugerencias.as_view(),
        name='solicitud_ali_reclamos_sugerencias'
    ),
    url(
        r'^solicitud/aula/$',
        SolicitudAulaView.as_view(),
        name='solicitud_aula'
    ),
    url(
        r'^solicitud/instalacion_software/$',
        SolicitudInstalacionSoftwareView.as_view(),
        name='solicitud_instalacion_software'
    ),
    url(
        r'^solicitud/laboratorio/informatica/$',
        SolicitudLaboratorioInformaticoView.as_view(),
        name='solicitud_laboratorio_informatico'
    ),
    url(
        r'^solicitud/material_multimedia/$',
        SolicitudMaterialMultimediaView.as_view(),
        name='solicitud_material_multimedia'
    ),
    url(
        r'^tv/cuerpos/$',
        TvCuerposListView.as_view(),
        name='tv_cuerpos'
    ),
    url(
        r'^tv/visor/(?P<slug>[-\w]+)/$',
        TvVisorDetailView.as_view(),
        name='tv_visor'
    ),
    url(
        r'^tv/visor/(?P<slug>[-\w]+)/cuerpos/$',
        TvVisorCuerposDetailView.as_view(),
        name='tv_visor_cuerpos'
    ),

    url(
        r'^solicitud/nueva/$',
        SolicitudCreate,
        name='solicitud_nueva'
    ),

    url(
        r'^api/materia/(?P<legajo>\d+)$',
        get_materia_json,
        name='materia_json'
    ),

    url(
        r'^api/horarios/(?P<comision>\d+)$',
        get_horarios_json,
        name='comision_json'
    ),
    url(
        r'^solicitudes/$',
        login_required(SolicitudList.as_view()),
        name='solicitud_listar'),
    url(
        r'^solicitud/(?P<pk>\d+)/$',
        login_required(SolicitudDetail.as_view()),
        name='solicitud_detalle'),
    url(
        r'^solicitud/baja/(?P<pk>\d+)/$',
        login_required(SolicitudReject),
        name='solicitud_baja'),

    url(
        r'^recurso/asignar/(?P<solicitud>\d+)/(?P<horario>\d+)$',
        login_required(RecursoAssign),
        name='recurso_assign'
    ),
    url(
        r'^mis_reservas/$',
        login_required(ReservaListDocente.as_view()),
        name='mis_reservas'),
    url(
        r'^reservas/crear/$',
        login_required(ReservaCreate),
        name='reserva_crear'),
    url(
        r'^reservas/listar/$',
        login_required(ReservaList.as_view()),
        name='reserva_listar'),
    url(
        r'^tv/novedad/(?P<slug>[-\w]+)/$',
        NovedadView.as_view(),
        name='tv_visor'
    ),
    # TODO: Eliminar. Vistas obsoletas debido a las vistas de VisorTv. Sólo se
    # mantienen para compatibilidad con los visores que funcionan actualmente.
    url(
        r'^tv/bedelia/(?P<slug>[-\w]+)/$',
        TvVisorDetailView.as_view(),
        name='tv_bedelia'
    ),
    url(
        r'^tv/bedelia/(?P<slug>[-\w]+)/cuerpos/$',
        TvVisorCuerposDetailView.as_view(),
        name='tv_bedelia_cuerpos'
    ),


    # Ali Prestamos
    url(
        r'^prestamos/registrar/$',
        login_required(PrestamoRegister),
        name='prestamo_registar'),

    url(
        r'^prestamos/crear/$',
        login_required(PrestamoCreate),
        name='prestamo_crear'),

    url(
        r'^prestamos/detalle/(?P<pk>\d+)$',
        login_required(PrestamoDetail.as_view()),
        name='prestamo_detalle'),

    url(
        r'^prestamos/finalizar/(?P<pk>\d+)/$',
        login_required(PrestamoFinalize),
        name='prestamo_finalizar'),
    url(
        r'^prestamos/listar/$',
        login_required(PrestamoList.as_view()),
        name='prestamo_listar'),
    url(
        r'^prestamos/agregar_elemento/$',
        login_required(PrestamoElementAdd),
        name='prestamo_agregar_elemento'),
    url(
        r'^prestamos/quitar_elementos/$',
        login_required(PrestamoElementsRemove),
        name='prestamo_quitar_elementos'),
    url(
        r'^prestamos/confirmar/$',
        login_required(PrestamoConfirm),
        name='prestamo_confirmar'),

    # Administración de usuarios
    url(
        r'^administracion_usuarios/$',
        login_required(UserList),
        name='user_roles'
    ),
    url(
        r'^administracion_fechas_semestre/$',
        login_required(FechasSemestreConfig),
        name='fechas_semestre_config'
    ),
    url(
        r'^administracion_usuarios/asignar/(?P<role>[A-Za-z]+)/(?P<pk>\d+)$',
        login_required(AsingRole),
        name='user_asing_role'
    ),
    url(
        r'^administracion_usuarios/quitar/(?P<role>[A-Za-z]+)/(?P<pk>\d+)$',
        login_required(RemoveRole),
        name='user_remove_role'
    ),

    url(
        r'^api/data/horarios/$',
        get_horarios,
        name='horario_json'
    ),
    url(
        r'^api/data/especialidades/$',
        get_especialidades,
        name='especialidades_json'
    ),
    url(
        r'^api/data/materias/$',
        get_materias,
        name='materias_json'
    ),
    url(
        r'^api/data/alumnos/$',
        get_alumnos,
        name='alumnos_json'
    ),
    url(
        r'^api/data/comision/(?P<anio>\d+)/$',
        get_comisiones_docentes,
        name='comision_json'
    ),

    url(
        r'^api/data/cursado/(?P<anio>\d+)/(?P<legajo>\d+)/$',
        get_cursado,
        name='horario_json'
    ),
    url(r'^administracion_aulas/listas_comisiones/$',
        HorariosWeekView,
        name='comisiones_listar'),

    url(r'^administracion_aulas/horario_comisiones/$',
        HorariosComisionListView.as_view(),
        name='comisiones_listar'),
]
